#!/bin/bash
#
# Quick setup script for MinIO configuration
# Pre-configures Litestream for MinIO at 192.168.1.173
#

set -euo pipefail

MINIO_ENDPOINT="192.168.1.173"
MINIO_PORT="9000"
LITESTREAM_CONFIG="/etc/litestream.yml"

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root (use sudo)"
    exit 1
fi

echo "MinIO Configuration Helper"
echo "=========================="
echo
echo "MinIO Server: ${MINIO_ENDPOINT}:${MINIO_PORT}"
echo

# Test connectivity
echo "Testing connectivity to MinIO server..."
if ping -c 1 -W 2 "${MINIO_ENDPOINT}" &>/dev/null; then
    echo "✓ MinIO server is reachable"
else
    echo "✗ Cannot reach MinIO server at ${MINIO_ENDPOINT}"
    echo "  Please verify the server is running and accessible"
    exit 1
fi

# Test port
if command -v nc &>/dev/null; then
    if nc -zv -w 2 "${MINIO_ENDPOINT}" "${MINIO_PORT}" &>/dev/null; then
        echo "✓ MinIO port ${MINIO_PORT} is accessible"
    else
        echo "⚠ Cannot connect to port ${MINIO_PORT} on ${MINIO_ENDPOINT}"
        echo "  Continuing anyway..."
    fi
fi

echo
read -p "Bucket name [sip-routing]: " BUCKET_NAME
BUCKET_NAME=${BUCKET_NAME:-sip-routing}

read -p "Path in bucket [routing.db]: " BUCKET_PATH
BUCKET_PATH=${BUCKET_PATH:-routing.db}

read -p "MinIO Access Key ID: " ACCESS_KEY
if [[ -z "$ACCESS_KEY" ]]; then
    echo "Error: Access Key ID is required"
    exit 1
fi

read -p "MinIO Secret Access Key: " SECRET_KEY
if [[ -z "$SECRET_KEY" ]]; then
    echo "Error: Secret Access Key is required"
    exit 1
fi

read -p "Use HTTPS? (y/N): " -n 1 -r
echo
USE_HTTPS=false
if [[ $REPLY =~ ^[Yy]$ ]]; then
    USE_HTTPS=true
    PROTOCOL="https"
    SKIP_VERIFY="false"
    read -p "Skip TLS verification? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        SKIP_VERIFY="true"
    fi
else
    PROTOCOL="http"
    SKIP_VERIFY="true"
fi

ENDPOINT="${PROTOCOL}://${MINIO_ENDPOINT}:${MINIO_PORT}"

# Create config
echo
echo "Creating Litestream configuration..."

if [[ -f "$LITESTREAM_CONFIG" ]]; then
    BACKUP="${LITESTREAM_CONFIG}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "Backing up existing config to ${BACKUP}..."
    cp "$LITESTREAM_CONFIG" "$BACKUP"
fi

cat > "$LITESTREAM_CONFIG" <<EOF
# Litestream configuration for Kamailio routing database
# Generated by setup-minio.sh on $(date)
# MinIO Server: ${ENDPOINT}

dbs:
  - path: /var/lib/kamailio/routing.db
    replicas:
      - type: s3
        bucket: ${BUCKET_NAME}
        path: ${BUCKET_PATH}
        endpoint: ${ENDPOINT}
        access-key-id: ${ACCESS_KEY}
        secret-access-key: ${SECRET_KEY}
        skip-verify: ${SKIP_VERIFY}
EOF

chmod 600 "$LITESTREAM_CONFIG"
chown root:root "$LITESTREAM_CONFIG"

echo "✓ Litestream configuration created at ${LITESTREAM_CONFIG}"
echo
echo "Configuration summary:"
echo "  Endpoint: ${ENDPOINT}"
echo "  Bucket: ${BUCKET_NAME}"
echo "  Path: ${BUCKET_PATH}"
echo
echo "Next steps:"
echo "  1. Ensure the bucket '${BUCKET_NAME}' exists in MinIO"
echo "  2. Start Litestream: sudo systemctl start litestream"
echo "  3. Verify replication: litestream databases"
