#!/bin/bash
#
# Setup database credentials file for helper scripts
# This creates /etc/opensips/.mysql_credentials if it doesn't exist
#
# Usage: sudo ./scripts/setup-db-credentials.sh [password]
#

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root (use sudo)"
    exit 1
fi

CRED_FILE="/etc/opensips/.mysql_credentials"

# Get password
if [[ $# -ge 1 ]]; then
    DB_PASSWORD="$1"
else
    echo "Enter MySQL database password for user 'opensips':"
    read -sp "" DB_PASSWORD
    echo
fi

if [[ -z "$DB_PASSWORD" ]]; then
    echo "Error: Password cannot be empty"
    exit 1
fi

# Check if file already exists
if [[ -f "$CRED_FILE" ]]; then
    echo "Credentials file already exists at ${CRED_FILE}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted"
        exit 0
    fi
fi

# Escape password for shell script
escaped_pass=$(printf '%q' "$DB_PASSWORD")

# Create credentials file
cat > "$CRED_FILE" <<EOF
# MySQL database credentials for OpenSIPS helper scripts
# This file is automatically generated by install.sh
# DO NOT edit manually - it will be overwritten on reinstall

DB_NAME="opensips"
DB_USER="opensips"
DB_PASS=${escaped_pass}
EOF

# Set restrictive permissions (readable only by root)
chmod 600 "$CRED_FILE"
chown root:root "$CRED_FILE"

echo "Credentials file created at ${CRED_FILE}"
echo "Helper scripts can now use it automatically (when run with sudo)"
